### ISSUE TITLE
快速上手第三步 上传密钥失败

### ISSUE THREAD

**Issue by Zengm2008** [secretflow/trustedflow#13]
cms register-data-keys
Traceback (most recent call last):
  File "/home/zchain/miniconda3/envs/sf/bin/cms", line 5, in <module>
    from cli.cms import cms
  File "/home/zchain/miniconda3/envs/sf/lib/python3.8/site-packages/cli/cms.py", line 20, in <module>
    from sdc import capsule_manager_frame
  File "/home/zchain/miniconda3/envs/sf/lib/python3.8/site-packages/sdc/capsule_manager_frame.py", line 28, in <module>
    from sdc.ual import ual
  File "/home/zchain/miniconda3/envs/sf/lib/python3.8/site-packages/sdc/ual/ual.py", line 23, in <module>
    from secretflowapis.v2.sdc import ual_pb2
ModuleNotFoundError: No module named 'secretflowapis.v2'

**Comment by yuki252111** [comment]
It seems that the python working directory is not found, maybe you can try execute command: export PYTHONPATH=.（If your python directory is the current directory）
