### ISSUE TITLE
cms register-data-policy报错

### ISSUE THREAD

**Issue by yali930709** [secretflow/trustedflow#33]
<采用仿真模式，参照https://www.secretflow.org.cn/zh-CN/docs/trustedflow/main/quick_start/step3 进行数据授权，报如下错误：
 Traceback (most recent call last):
  File "/usr/local/bin/cms", line 8, in <module>
    sys.exit(cms())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/cli/cms.py", line 184, in register_data_policy
    ctx.obj.create_data_policy(
  File "/usr/local/lib/python3.8/dist-packages/sdc/capsule_manager_frame.py", line 489, in create_data_policy
    for index in range(len(rule_ids)):
TypeError: object of type 'NoneType' has no len()
具体的cli.yaml配置：
register_data_policy:
  scope: default
  data_uuid: breast_cancer_bob
  grantee_party_ids: 
    -
      - LPSZB6L446NS2P3I3NUCQZEX2SG2EQSJZ2QNXZSE2W56INE7LZ3Q
  columns: 
    -
      - id
      - mean radius
      - mean texture
      - mean perimeter
      - mean area
      - mean smoothness
  global_constraints: null
  op_constraints_body: null
  op_constraints_name: 
    - 
      - OP_PSI
      - OP_DATASET_SPLIT
      - OP_XGB
      - OP_PREDICT
      - OP_BICLASSIFIER_EVALUATION
  rule_ids: null
这里rule_ids要怎么填写，有没有关于数据授权的配置文件修改指定文档？>

<details>
      <summary>技术信息</summary>
      <ul>
        <li>页面 <a href="https://www.secretflow.org.cn/zh-CN/docs/trustedflow/main/quick_start/step3">https://www.secretflow.org.cn/zh-CN/docs/trustedflow/main/quick_start/step3</a></li>
        <li>源码 <a href="https://github.com/secretflow/trustedflow/blob/47d96c25b320d6c2faae3332aed4d1b83b6b9872/docs/quick_start/step3.ipynb">https://github.com/secretflow/trustedflow/blob/47d96c25b320d6c2faae3332aed4d1b83b6b9872/docs/quick_start/step3.ipynb</a></li>
        <li>浏览器 <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0</code></li>
      </ul>
    </details>

**Comment by zhongtianq** [comment]
@yali930709 hi，新版的文档已经发布了，麻烦您重新拉取一下最新镜像和模版文件。关于rule_id，如上面所说，还是由您自定义填写即可。
