### ISSUE TITLE
在SGX模式下计算PSI时出错

### ISSUE THREAD

**Issue by zzx-QDU** [secretflow/trustedflow#48]
### Issue Type

Bug

### Source

binary

### Capsule Manager Version

0.2.0b0

### Capsule Manager SDK Version

0.2.0b0

### Tee Apps Version

0.2.0b0

### OS Platform and Distribution

Ubuntu 22.04

### Python version

3.10

### What happend and What you expected to happen.

```shell
大佬，您好！我在SGX模式下运行示例到执行PSI计算时出错，且报错信息有多种：
第一种：
thread '<unnamed>' panicked at 'failed to sync when dropping the SEFS Inode: DeviceError(5)', /tmp/deb_build/occlum-0.30.1/occlum-src/deps/sefs/rcore-fs-sefs/src/lib.rs:805:14
stack backtrace:
note: Some details are omitted, call backtrace::enable_backtrace() with 'PrintFormat::Full' for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
/opt/occlum/build/bin/occlum: line 472:   167 Illegal instruction     (core dumped) RUST_BACKTRACE=1 "$instance_dir/build/bin/occlum-run" "$@"

第二种：
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /tmp/deb_build/occlum-0.30.1/occlum-src/deps/sefs/rcore-fs-unionfs/src/lib.rs:543:24
stack backtrace:
note: Some details are omitted, call backtrace::enable_backtrace() with 'PrintFormat::Full' for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
/opt/occlum/build/bin/occlum: line 472:   199 Illegal instruction     (core dumped) RUST_BACKTRACE=1 "$instance_dir/build/bin/occlum-run" "$@"

配置中除了SGX模式特有的，其余都在仿真模式下测试过。请问可能是什么原因导致出错？
```

### Reproduction code to reproduce the issue.

```shell
无。
```

**Comment by zzx-QDU** [comment]
capsule-manager只输出了下面的信息，没有报错。

[2024-05-06 10:00:05.059] [info] [sgx2_generator.cc:102] Start generating sgx2 report
[2024-05-06 10:00:05.095] [info] [sgx2_generator.cc:134] Get sgx2 quote succeed
[2024-05-06 10:00:05.095] [info] [sgx2_generator.cc:142] Start getting sgx2 collateral
[2024-05-06 10:00:05.116] [info] [sgx2_generator.cc:149] Get sgx2 collateral succeed
[2024-05-06 10:00:05.116] [info] [sgx2_generator.cc:158] Generate sgx2 report succeed
[2024-05-06 10:00:05.118] [info] [generator_wrapper_c_api.cc:67] report len: 32773
[2024-05-06 10:00:05.118] [info] [generator_wrapper_c_api.cc:77] GenerateAttestationReport success
[2024-05-06T10:00:05.120912093+00:00] [monitor] [INFO] |get_ra_cert|0|"success"
[2024-05-06T10:00:05.323432184+00:00] [monitor] [INFO] |get_data_keys|0|"success"

**Comment by zhongtianq** [comment]
@zzx-QDU 请问上面occlum报错是teeapps的报错吗？可以把/home/teeapp/occlum/occlum_instance/logs/app.log内容贴一下吗？

**Comment by zzx-QDU** [comment]
最后一次执行的log：
2024-05-07 02:45:52.522 [info] [log.cc:SetupLogger:81] Initialize logger app_log succeed.
2024-05-07 02:45:52.523 [info] [log.cc:SetupLogger:81] Initialize logger monitor_log succeed.
2024-05-07 02:45:52.523 [info] [app.cc:App:94] Start parsing Local Task Config...
2024-05-07 02:45:52.525 [info] [app.cc:App:100] Parsing Local Task Config succeed
2024-05-07 02:45:53.056 [info] [app.cc:App:125] Gen teeapps private key and certificate success
2024-05-07 02:45:53.059 [info] [app.cc:App:130] Create Capsule Manager Client success
2024-05-07 02:45:53.059 [info] [app.cc:PreProcess:273] Starting pre-processing, component preprocessing-psi-0.0.1...
2024-05-07 02:45:53.059 [info] [app.cc:GetInputDataKeys:212] Try to get Ra Cert from Capsule Manager
2024-05-07 02:45:53.185 [info] [app.cc:GetInputDataKeys:214] Got Ra Cert
2024-05-07 02:45:53.185 [info] [app.cc:GetInputDataKeys:215] Try to get data keys from Capsule Manager
2024-05-07 02:45:53.185 [info] [capsule_manager_client.cc:GetDataKeys:109] Serializing resource_req...
2024-05-07 02:45:53.185 [info] [capsule_manager_client.cc:GetDataKeys:114] Generating attestation report...
2024-05-07 02:45:53.186 [info] [sgx2_generator.cc:GenerateReport:102] Start generating sgx2 report
2024-05-07 02:45:53.253 [info] [sgx2_generator.cc:GenerateReport:134] Get sgx2 quote succeed
2024-05-07 02:45:53.253 [info] [sgx2_generator.cc:GenerateReport:142] Start getting sgx2 collateral
2024-05-07 02:45:53.299 [info] [sgx2_generator.cc:GenerateReport:149] Get sgx2 collateral succeed
2024-05-07 02:45:53.300 [info] [sgx2_generator.cc:GenerateReport:158] Generate sgx2 report succeed
2024-05-07 02:45:53.390 [info] [app.cc:GetInputDataKeys:222] Got data keys
2024-05-07 02:45:53.390 [info] [app.cc:ProcessInput:236] Downloading Individual Table Or Model/Rule and Decryption...
2024-05-07 02:45:53.392 [info] [app.cc:ProcessInput:257] Decrypting /host/testdata/breast_cancer/alice.csv.enc ...
2024-05-07 02:45:53.393 [info] [app.cc:ProcessInput:262] Decrypting /host/testdata/breast_cancer/alice.csv.enc success
2024-05-07 02:45:53.393 [info] [app.cc:ProcessInput:236] Downloading Individual Table Or Model/Rule and Decryption...
2024-05-07 02:45:53.394 [info] [app.cc:ProcessInput:257] Decrypting /host/testdata/breast_cancer/bob.csv.enc ...
2024-05-07 02:45:53.395 [info] [app.cc:ProcessInput:262] Decrypting /host/testdata/breast_cancer/bob.csv.enc success
2024-05-07 02:45:53.395 [info] [task_config_util.cc:GenAndDumpTaskConfig:657] Generate Individual table's schema
2024-05-07 02:45:53.395 [info] [task_config_util.cc:GenAndDumpTaskConfig:657] Generate Individual table's schema
2024-05-07 02:45:53.395 [info] [task_config_util.cc:FillTaskConfigParams:610] Try to fill psi config params
2024-05-07 02:45:53.395 [info] [task_config_util.cc:FillTaskConfigParams:613] Fill psi config params success
2024-05-07 02:45:53.395 [info] [task_config_util.cc:GenAndDumpTaskConfig:692] Dumping task config json succeed...
2024-05-07 02:45:53.395 [info] [app.cc:PreProcess:293] Pre-processing, component preprocessing-psi-0.0.1 succeed...
2024-05-07 02:45:53.395 [info] [app.cc:ExecCmd:299] Start executing, component preprocessing-psi-0.0.1...
2024-05-07 02:45:53.396 [info] [app.cc:ExecCmd:302] Launch command: /bin/python3,/psi.py

**Comment by zhongtianq** [comment]
@zzx-QDU psi的任务配置有修改什么吗？

**Comment by zzx-QDU** [comment]
没有任何修改

**Comment by zhongtianq** [comment]
@zzx-QDU 前面你提问中提到。配置中除了SGX模式特有的，其余都在仿真模式下测试过。这个SGX特有的你是修改了什么吗

**Comment by zhongtianq** [comment]
我看你最前面贴的occlum的报错信息，翻越了一下occlum代码，是occlum文件系统相关的部分，是不是没有把文件路径放对？

https://www.secretflow.org.cn/zh-CN/docs/trustedflow/0.2.0b0.post0/quick_start/step4#id11

**Comment by zzx-QDU** [comment]
alice.csv.enc  bob.csv.enc都在/home/teeapp/occlum/occlum_instance/testdata/breast_cancer/
carol.crt  carol.key psi_task.json都在/home/teeapp/occlum/occlum_instance/integration_test/

**Comment by zzx-QDU** [comment]
配置文件中只添加了度量值并将sim改为sgx。

**Comment by zzx-QDU** [comment]
我在仿真模式下运行./main --plat=sim --enable_console_logger=true --enable_capsule_tls=false --entry_task_config_path=/host/integration_test/psi_task.json会正常生成task文件夹及其下的文件，
但在sgx模式下，运行occlum run /bin/main --plat=sgx --enable_console_logger=true --enable_capsule_tls=false --entry_task_config_path=/host/integration_test/psi_task.json却没有生成task文件夹和相应的文件。
请问这是我配置弄错了还是镜像有问题？

**Comment by zhongtianq** [comment]
@zzx-QDU 应该不是你说的没有配置文件的问题，/home/teeapp/task/task_config.json这个是运行时内部生成的文件，occlum模式下看不到是因为occlum使用了加密文件系统，你看不到但是实际是存在的。

我本地又运行了一下整个流程，没有遇到你这个问题。根据你提供的日志，主要流程都已经运行完了，在最后运行python代码的时候直接退出了。因为psi代码进入后第一步首先会打印一些下面这样的信息
```bash
[info] [app.cc:ExecCmd:308] stdout:
 INFO:root:Reading config file...
INFO:root:Running psi...
```

先排除一下环境问题吧：
首先确认一下teeapps的occlum镜像是最新的版本，然后可以在/home/teeapp/occlum/occlum_instance目录下自己新建一个python文件，比如test.py，随便写一些你要执行的逻辑。  然后occlum run /bin/python3 /host/test.py看看是否能成功执行。

**Comment by zzx-QDU** [comment]
我按您说的进行了验证，环境没有问题。然后，我重新一步一步地跑了一遍，还是出现同样的错误。您觉得大概是什么地方出了问题，我想缩小排查的范围。

**Comment by zhongtianq** [comment]
远程支持排查后操作流程没有问题，也运行完主要步骤。在最后拉起psi组件的时候occlum会异常退出，怀疑与主机配置有关，转到occlum下提issue解决了。
此issue先关闭了，后续如有反馈再跟进

**Comment by zzx-QDU** [comment]
@zhongtianq occlum的反馈是硬件资源受限制导致的，通过ulimate增加硬件资源后问题就解决了。

**Comment by zhongtianq** [comment]
贴一下解决问题的地址
https://github.com/occlum/occlum/issues/1537
